### PR TITLE
Fix/beta diversity

### LINKED ISSUE #7: Fix the beta-diversity analysis
Clean the spaghetti code in the beta diversity part of the package.

1. I was thinking much too complex when designing this. Let's stay with single, classic PCOAS for now + PERMANOVAs + Dispersion tests. Allow for groups with multiple levels (2+) to be tested as well.
2. Add t-SNEs, both computing + plotting logic.
3.  Discuss with Alex how he did the PERMANOVA analyses on the single-taxon level. If the results are great, i could implement this as another analysis module.
4. Remove the complex plots and analysis logic for continuous time.
5. Improve the documentation

### PR DESCRIPTION
**Pull request by Polymerase3**
### **User description**
Solution to issue https://github.com/Polymerase3/phiper/issues/7

___

### **PR Type**
Enhancement, Bug fix, Tests, Documentation

___

### **Description**
- Implemented comprehensive beta diversity analysis module with six core functions: `compute_distance()`, `compute_pcoa()`, `compute_capscale()`, `compute_permanova()`, `compute_dispersion()`, and `compute_tsne()`

- Added distance matrix computation supporting multiple normalization methods and distance metrics via `parallelDist` and `vegan` packages

- Implemented principal coordinates analysis (PCoA) with negative eigenvalue correction and feature-axis associations

- Added constrained ordination (CAP/db-RDA) with variance partitioning and permutation tests

- Implemented PERMANOVA testing with global and pairwise post-hoc contrasts, supporting stratified permutations for repeated measures

- Created comprehensive visualization functions: `plot_pcoa()`, `plot_cap()`, `plot_scree()`, `plot_dispersion()`, and `plot_tsne()` with support for grouping, time factors, centroids, and ellipses

- Added specialized time-series plotting functions: `ph_plot_cap_axes_vs_time()`, `ph_plot_dispersion_vs_time()`, and `ph_plot_dispersion_box()`

- Integrated package theming via `theme_phip()` and color palettes via `scale_color_phip()`

- Added complete test coverage for all beta diversity functions including happy paths, input validation, error handling, and edge cases

- Enhanced `scatter_interactive()` with background peptide visualization support

- Fixed special character encoding issue in alpha diversity plot labels (replaced `≥` with `>=`)

- Added dependencies: `parallelDist` (Suggests) and `Rtsne` (Imports)

- Refactored module structure by replacing old `binary-analysis_beta.R` and `binary-analysis_beta_plots.R` with new `binary_beta.R` and `binary_beta_plots.R`

___

### Diagram Walkthrough

```mermaid
flowchart LR
  A["Distance Matrix<br/>compute_distance"] --> B["PCoA<br/>compute_pcoa"]
  A --> C["CAP/db-RDA<br/>compute_capscale"]
  A --> D["PERMANOVA<br/>compute_permanova"]
  A --> E["Dispersion<br/>compute_dispersion"]
  A --> F["t-SNE<br/>compute_tsne"]
  B --> G["plot_pcoa"]
  B --> H["plot_scree"]
  C --> I["plot_cap"]
  C --> J["ph_plot_cap_axes_vs_time"]
  E --> K["plot_dispersion"]
  E --> L["ph_plot_dispersion_vs_time<br/>ph_plot_dispersion_box"]
  F --> M["plot_tsne"]
```

<details><summary><h3>File Walkthrough</h3></summary>

<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>3 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>binary_beta.R</strong><dd><code>Complete beta diversity analysis module implementation</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

R/binary_beta.R

<ul><li>Added comprehensive beta diversity analysis functions: <br><code>compute_distance()</code>, <code>compute_pcoa()</code>, <code>compute_capscale()</code>, <br><code>compute_permanova()</code>, <code>compute_dispersion()</code>, and <code>compute_tsne()</code><br> <li> Implemented distance matrix computation with support for multiple <br>normalization methods and distance metrics via <code>parallelDist</code> or <code>vegan</code> <br>packages<br> <li> Added principal coordinates analysis (PCoA) with negative eigenvalue <br>correction and feature-axis associations<br> <li> Implemented constrained ordination (CAP/db-RDA) with variance <br>partitioning and permutation tests<br> <li> Added PERMANOVA testing with global and pairwise post-hoc contrasts, <br>supporting stratified permutations for repeated measures</ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-da1e2eaf6bdf7ec8de45972fe407988d56de46b728468acdded4f546c82adcbc">+2567/-0</a></td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>binary_beta_plots.R</strong><dd><code>Beta diversity visualization functions with ordination and dispersion </code><br><code>plots</code></dd></summary>
<hr>

R/binary_beta_plots.R

<ul><li>Added comprehensive plotting functions for beta diversity analysis: <br><code>plot_pcoa()</code>, <code>plot_cap()</code>, <code>plot_scree()</code>, <code>plot_dispersion()</code>, and <br><code>plot_tsne()</code><br> <li> Implemented support for PCoA and CAP/db-RDA ordination visualizations <br>with optional grouping, time factors, centroids, and ellipses<br> <li> Added specialized plotting functions for continuous time analysis: <br><code>ph_plot_cap_axes_vs_time()</code>, <code>ph_plot_dispersion_vs_time()</code>, and <br><code>ph_plot_dispersion_box()</code><br> <li> All plotting functions integrate with package theming via <code>theme_phip()</code> <br>and color palettes via <code>scale_color_phip()</code></ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-2f1146eb7d0b34f9cd46ef797ccde1467b163fa728940d3acf252e4fe89dded1">+1715/-0</a></td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>scatter_interactive.Rd</strong><dd><code>Enhanced scatter_interactive with background peptide visualization</code></dd></summary>
<hr>

man/scatter_interactive.Rd

<ul><li>Added new parameters for background peptide visualization: <code>peplib</code>, <br><code>category_colors</code>, <code>show_background</code>, <code>background_df</code>, <code>background_name</code>, <br><code>background_color</code>, <code>background_size</code>, <code>background_alpha</code>, <code>background_max_n</code>, <br><code>background_seed</code><br> <li> Added point styling parameters: <code>point_line_width</code> and <code>point_line_color</code><br> <li> Enhanced interactive scatter plot with background peptide layer <br>support</ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-32713d4ea632d834952eb61567ecd00334df15fde2956f1f6191911e788add22">+13/-0</a>&nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Tests</strong></td><td><details><summary>2 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>test-binary_alpha.R</strong><dd><code>Disabled alpha diversity test suite</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tests/testthat/test-binary_alpha.R

<ul><li>Commented out all 139 lines of existing alpha diversity tests<br> <li> Tests remain in file but are disabled, likely pending refactoring or <br>replacement</ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-bfb379cadf0ae0b236ecaff74e728dfdb4775f1d0aa9ff9e1adc0cb0f037bcad">+139/-139</a></td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>test-binary_beta.R</strong><dd><code>Complete test coverage for beta diversity analysis functions</code></dd></summary>
<hr>

tests/testthat/test-binary_beta.R

<ul><li>Comprehensive test suite for beta diversity functions including <br><code>compute_distance</code>, <code>compute_pcoa</code>, <code>compute_capscale</code>, <code>compute_permanova</code>, <br><code>compute_dispersion</code>, and <code>compute_tsne</code><br> <li> Tests cover happy paths, input validation, error handling, edge cases, <br>reproducibility, and integration scenarios<br> <li> Includes helper functions for test data setup and constraint variable <br>selection<br> <li> Tests verify output structure, types, numerical accuracy, and proper <br>handling of missing data and invalid inputs</ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-7aeaf0af82cf43390272d53a18ee7ae5762412d42de94e7e1c9f161d4f2215b5">+2348/-0</a></td>

</tr>
</table></details></td></tr><tr><td><strong>Documentation</strong></td><td><details><summary>11 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>compute_capscale.Rd</strong><dd><code>Documentation for constrained ordination function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

man/compute_capscale.Rd

<ul><li>Generated roxygen2 documentation file for <code>compute_capscale()</code> function<br> <li> Documents function signature, parameters, return value structure, and <br>includes executable examples<br> <li> Provides detailed descriptions of constrained ordination analysis and <br>feature associations</ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-c55b39ca8b4408ca42c1684ad046aee8e30145e779ca737f175a5328a8fe4cde">+138/-0</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>plot_pcoa.Rd</strong><dd><code>Documentation for PCoA plotting function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

man/plot_pcoa.Rd

<ul><li>New documentation for <code>plot_pcoa</code> function for visualizing PCoA results<br> <li> Documents parameters for axes selection, grouping, time factors, <br>centroids, ellipses, and visual styling<br> <li> Includes usage examples and details on variance explained annotations</ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-3a88282cd6b04010d5873d5748ba1f065c7d1953e565d89633f6546b702d03cf">+134/-0</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>plot_cap.Rd</strong><dd><code>Documentation for CAP ordination plotting function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

man/plot_cap.Rd

<ul><li>New documentation for <code>plot_cap</code> function for constrained ordination <br>(CAP/db-RDA) visualization<br> <li> Documents parameters for axes, grouping, time factors, centroids, <br>ellipses, and styling options<br> <li> Includes examples and details on variance explained calculations</ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-a417919be30145f9617d2685f5eb945909ed1471071a93e38d8601b1a0342738">+130/-0</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>compute_permanova.Rd</strong><dd><code>Documentation for PERMANOVA statistical testing function</code>&nbsp; </dd></summary>
<hr>

man/compute_permanova.Rd

<ul><li>New documentation for <code>compute_permanova</code> function performing PERMANOVA <br>tests on distance matrices<br> <li> Documents parameters for distance object, metadata, grouping/time <br>factors, subject stratification, and permutation settings<br> <li> Describes output tibble structure with test results and p-value <br>adjustments</ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-004be969eabe29b5d1c9e2cd5418873a6578e377ec54c0b7c418d0fb8e17386e">+142/-0</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>compute_pcoa.Rd</strong><dd><code>Documentation for PCoA analysis function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

man/compute_pcoa.Rd

<ul><li>New documentation for <code>compute_pcoa</code> function performing Principal <br>Coordinates Analysis<br> <li> Documents parameters for distance object, negative eigenvalue <br>correction, axis count, and feature associations<br> <li> Describes output list structure including sample coordinates, <br>eigenvalues, variance explained, and feature associations</ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-c5d987987e13a8dd875170a371501aea69009a82ffd2285aea7d2df6a57448fc">+129/-0</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>plot_dispersion.Rd</strong><dd><code>Documentation for beta dispersion plotting function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

man/plot_dispersion.Rd

<ul><li>New documentation for <code>plot_dispersion</code> function visualizing beta <br>dispersion results<br> <li> Documents parameters for scope/contrast selection, violin/box/point <br>display options, and styling<br> <li> Includes examples showing global and pairwise dispersion plots</ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-c1bc40b029d70239f9c08a9cece533e6ea6f9fed217c6d78b362113e935d8adb">+81/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>compute_distance.Rd</strong><dd><code>Documentation for distance computation function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

man/compute_distance.Rd

<ul><li>Added documentation for <code>compute_distance()</code> function that computes <br>pairwise sample distances<br> <li> Documents support for multiple distance methods via <code>parallelDist</code> and <br><code>vegan</code> packages<br> <li> Includes normalization options and multi-threaded computation support</ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-280753b952ffc6c104338d84a2836a99127753683f6e45aab12126574908efd6">+134/-0</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>compute_tsne.Rd</strong><dd><code>Documentation for t-SNE embedding computation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

man/compute_tsne.Rd

<ul><li>Added documentation for <code>compute_tsne()</code> function for t-SNE embeddings<br> <li> Documents parameters for dimensionality reduction (2D/3D), perplexity, <br>and metadata attachment<br> <li> Includes examples showing integration with <code>phip_data</code> objects and <br>distance matrices</ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-d7c5119751aa26b50736623636a1155d231b0e55d716e6d91aa45be7007c0055">+152/-0</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>compute_dispersion.Rd</strong><dd><code>Documentation for beta dispersion testing function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

man/compute_dispersion.Rd

<ul><li>Added documentation for <code>compute_dispersion()</code> function testing <br>homogeneity of dispersion<br> <li> Documents beta dispersion analysis with group and time factors<br> <li> Includes permutation testing and p-value adjustment options</ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-35e2c7ff05a9c664950cb3836521a8a76612c014492460506238870b77635ea0">+110/-0</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>plot_tsne.Rd</strong><dd><code>Documentation for t-SNE plotting function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

man/plot_tsne.Rd

<ul><li>Added documentation for <code>plot_tsne()</code> function supporting 2D and 3D <br>visualizations<br> <li> Documents parameters for color mapping, point styling, and palette <br>customization<br> <li> Specifies return types: <code>ggplot</code> for 2D and <code>plotly</code> widget for 3D</ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-5bc20fa62765f1fe33e540e765c4d3e06e0a9eccac4362279c5ebe584c2f900d">+57/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>plot_scree.Rd</strong><dd><code>Documentation for PCoA scree plot function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

man/plot_scree.Rd

<ul><li>Added documentation for <code>plot_scree()</code> function creating scree plots <br>from PCoA eigenvalues<br> <li> Documents bar and line plot types for variance explained visualization<br> <li> Includes handling of negative eigenvalues from non-Euclidean distance <br>matrices</ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-c60261893d84139916e5680fd51e4335b02c3c05355f654715d143aec57e46d4">+43/-0</a>&nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Bug fix</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>binary_alpha_plots.R</strong><dd><code>Fix special character encoding in plot label</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

R/binary_alpha_plots.R

<ul><li>Minor fix: replaced special character <code>≥</code> with ASCII equivalent <code>>=</code> in <br>plot label text for better compatibility</ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-c7bf848374d9200d90c6233c36640f952b13d9eb27368f0cef200703f6dd09b7">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Configuration changes</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>NAMESPACE</strong><dd><code>Updated exports for new beta diversity analysis functions</code></dd></summary>
<hr>

NAMESPACE

<ul><li>Removed S3 method exports for <code>compute_beta_diversity</code> and <br><code>print.phip_beta_diversity</code><br> <li> Added exports for new beta diversity functions: <code>compute_capscale()</code>, <br><code>compute_dispersion()</code>, <code>compute_distance()</code>, <code>compute_pcoa()</code>, <br><code>compute_permanova()</code>, <code>compute_tsne()</code><br> <li> Added export for <code>plot_tsne()</code> visualization function</ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-b6b6854a02ae177f8860f49654ff250c1554d021ae434b6efdbe99d00bdc6055">+7/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Dependencies</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>DESCRIPTION</strong><dd><code>Added dependencies for distance and t-SNE computation</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

DESCRIPTION

<ul><li>Added <code>parallelDist</code> to Suggests for fast distance computation<br> <li> Added <code>Rtsne</code> to Imports for t-SNE dimensionality reduction<br> <li> Minor formatting fixes (removed trailing spaces)</ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-9cc358405149db607ff830a16f0b4b21f7366e3c99ec00d52800acebe21b231c">+5/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Miscellaneous</strong></td><td><details><summary>3 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>ph_plot_dispersion_vs_time.Rd</strong><dd><code>Fixed documentation source file reference</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

man/ph_plot_dispersion_vs_time.Rd

<ul><li>Updated documentation source file reference from <br><code>R/binary-analysis_beta_plots.R</code> to <code>R/binary_beta_plots.R</code></ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-da38781572dbe23cabaaf2488bc08a0b0d42e12712c7014ac68cdced2a2729a4">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>ph_plot_cap_axes_vs_time.Rd</strong><dd><code>Fixed documentation source file reference</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

man/ph_plot_cap_axes_vs_time.Rd

<ul><li>Updated documentation source file reference from <br><code>R/binary-analysis_beta_plots.R</code> to <code>R/binary_beta_plots.R</code></ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-04488231ad51dcb5238454ce2ccde999c3b90e9cb1ef0256db6d5af09c22ffc6">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>ph_plot_dispersion_box.Rd</strong><dd><code>Fixed documentation source file reference</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

man/ph_plot_dispersion_box.Rd

<ul><li>Updated documentation source file reference from <br><code>R/binary-analysis_beta_plots.R</code> to <code>R/binary_beta_plots.R</code></ul>

</details>

  </td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-5ca78d02b6936141e3e6ab05b6bc0a4c1f4e0aeabd5bdeb7d8a0b484787d1492">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Additional files</strong></td><td><details><summary>3 files</summary><table>
<tr>
  <td><strong>binary-analysis_beta.R</strong></td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-41b889c28cf26828374f46bd6c5a587316d179eae311dbc642e8679a339e412b">+0/-3225</a></td>

</tr>

<tr>
  <td><strong>binary-analysis_beta_plots.R</strong></td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-244c1371bdb0227fe39702b53cb5b61f4f37e7df6b89ff41b024600d33e16fc7">+0/-835</a>&nbsp; </td>

</tr>

<tr>
  <td><strong>compute_beta_diversity.Rd</strong></td>
  <td><a href="https://github.com/Polymerase3/phiper/pull/15/files#diff-b12c05a585788883b184cd778125dead18a331c4ed929e60dbe313655728ab9b">+0/-209</a>&nbsp; </td>

</tr>
</table></details></td></tr></tbody></table>

</details>

___

### CODE REVIEW

File: DESCRIPTION
Comment (Alon-Alexander) [inline DESCRIPTION]: We should start bumping versions in each PR (and keeping an up-to-date NEWS.md file).

I suggest you read about [semver](https://semver.org/) and we use that, as an unstable package (before 1.0.0).
The standard would mean that every major increase (or change before 1.0.0) would be a minor update (0.1.0 -> 0.2.0 for example) and every refactor/small thing would be a patch increase (0.2.3 -> 0.2.4 for example).
Only when we're stable we'd go to 1.0.0 and from that point, every API break (non backward compatible) is a major break (which means we should be quite cautious and smart).

File: R/binary_beta.R [hunk 1]
```diff
@@ -0,0 +1,2567 @@
...
+  if (!is.numeric(dat_small[[value_col]])) {
+    .ph_abort(
+      paste0("`", value_col, "` must be numeric after collect().")
+    )
+  }
+
+.ph_log_info("pivoting to wide abundance matrix in r.")
+
+  wide_df <- dat_small |>
+    tidyr::pivot_wider(
```
Comment (Alon-Alexander) [inline R/binary_beta.R]: If you use `dbplyr_pivot_wider_spec` (or [tidyr::pivot_wider_spec()](https://tidyr.tidyverse.org/reference/pivot_wider_spec.html) for the non-db-backed) then you only need to collect the unique values for `sample_id` and `peptide_id` instead of the entire data into memory.

I would try that as this might be faster and would certainly require less memory.

File: R/binary_beta.R [hunk 2]
```diff
@@ -0,0 +1,2567 @@
...
+  }
+
+.ph_log_info(
+  paste0("abundance matrix has ", nrow(mat), " samples and ",
+         ncol(mat), " features after preprocessing.")
+)
+
+  # ---------------------------------------------------------------------------
+  # 3) normalization
+  # ---------------------------------------------------------------------------
```
Comment (Alon-Alexander) [inline R/binary_beta.R]: This should be a small helper function

File: R/binary_beta.R [hunk 3]
```diff
@@ -0,0 +1,2567 @@
...
+      rs[rs == 0] <- 1
+      sqrt(mat / rs)
+    },
+    "log" = log1p(mat)
+  )
+
+  # ---------------------------------------------------------------------------
+  # 4) distance computation
+  # ---------------------------------------------------------------------------
+  if (dist_method == "chebyshev") dist_method <- "maximum"
```
Comment (Alon-Alexander) [inline R/binary_beta.R]: Add a log info/debug so that the user will know.
Also, in my opinion, **always** add curly brackets.

File: R/binary_beta.R [hunk 4]
```diff
@@ -0,0 +1,2567 @@
...
+
+  pd_methods <- c(
+    "bray", "euclidean", "minkowski", "manhattan", "canberra",
+    "binary", "maximum", "cosine"
+  )
+
+  use_pd <- dist_method %in% pd_methods
+
+  if (use_pd) {
+    if (!rlang::is_installed("parallelDist")) {
```
Comment (Alon-Alexander) [inline R/binary_beta.R]: Some of the `parallelDist` names are also valid for `vegan::vegdist` (like `bray`, `euclidean`, `manhattan`, etc.) and these should go to `vegan` even if `parallelDist` is not installed (instead of aborting).

File: R/binary_beta.R [hunk 5]
```diff
@@ -0,0 +1,2567 @@
...
+#'   exist             = "exist",
+#'   timepoint         = "timepoint_factor",
+#'   fold_change       = "fold_change",
+#'   materialise_table = TRUE,
+#'   auto_expand       = TRUE,
+#'   n_cores           = 2
+#' )
+#'
+#' # small subset for speed: 5 peptides at time t1
+#' keep_pep <- c("16627", "5243", "24799", "16196", "18003")
```
Comment (Alon-Alexander) [inline R/binary_beta.R]: I don't like these custom lines (also repeats multiple times).
We should have another "name" option in `phip_load_example_data` which returns such a small (hard-coded) object (like you wrote in some tests).

File: R/binary_beta.R [hunk 6]
```diff
@@ -0,0 +1,2567 @@
...
+#'   pcoa_res$sample_coords
+#'   pcoa_res$var_explained
+#'   pcoa_res$feature_associations
+#' }
+#' @export
+compute_pcoa <- function(dist_obj,
+                         neg_correction = c("none", "lingoes", "cailliez"),
+                         n_axes = 5L,
+                         top_features = 30L,
+                         feature_assoc = c("wa", "correlation",
```
Comment (Alon-Alexander) [inline R/binary_beta.R]: Why not call it the full `weighted_average`?

File: R/binary_beta.R [hunk 7]
```diff
@@ -0,0 +1,2567 @@
...
+  } else {
+    "No negative eigenvalue correction applied."
+  }
+
+  if (is_corrected) {
+    .ph_warn(correction_note)
+  }
+
+  eig_vals <- pcoa_fit$eig
+  if (is.null(eig_vals)) eig_vals <- numeric(0L)
```
Comment (Alon-Alexander) [inline R/binary_beta.R]: Should this happen? I would warn the user

File: R/binary_beta.R [hunk 8]
```diff
@@ -0,0 +1,2567 @@
...
+
+  coords <- as.matrix(pcoa_fit$points)
+  if (is.null(coords)) {
+    coords <- matrix(0, nrow = n, ncol = 0L)
+  }
+
+  # enforce stable axis and sample naming
+  if (ncol(coords) > 0L) {
+    colnames(coords) <- paste0("PCoA", seq_len(ncol(coords)))
+  }
```
Comment (Alon-Alexander) [inline R/binary_beta.R]: ❤️

File: R/binary_beta.R [hunk 9]
```diff
@@ -0,0 +1,2567 @@
...
+      0
+    }
+  } else {
+    pct_axes <- rep(NA_real_, k_use)
+    pct_other <- NA_real_
+  }
+
+  names(pct_axes) <- paste0("%PCoA", seq_len(k_use))
+  var_explained <- tibble::as_tibble_row(
+    c(as.list(round(pct_axes, 3)), `%Other` = round(pct_other, 3))
```
Comment (Alon-Alexander) [inline R/binary_beta.R]: I wouldn't round - let the user have the information and round it if and when they want

File: R/binary_beta.R [hunk 10]
```diff
@@ -0,0 +1,2567 @@
...
+
+    coords_ids <- rownames(coords)
+    X_ids <- rownames(X)
+
+    if (is.null(coords_ids) || is.null(X_ids)) {
+      .ph_warn(
+        "row names missing in coordinates or 'abundances'; cannot align samples
+        for feature associations."
+      )
+    } else {
```
Comment (Alon-Alexander) [inline R/binary_beta.R]: You have an anti-pattern here where you have a "brackets pyramid".
Once this is in a helper function, it will be very easy to just early `return` an empty result on every such problem instead of stacking the if clauses on top of one another.

File: R/binary_beta.R [hunk 11]
```diff
@@ -0,0 +1,2567 @@
...
+#' not replace a full repeated-measures permutation design (e.g., via
+#' \code{permute::how()}), especially for multi-level time with missing
+#' timepoints.
+#'
+#' P-values are optionally adjusted within each contrast scope (e.g.,
+#' \code{"group_pairwise"}, \code{"time_pairwise"}) using
+#' \code{stats::p.adjust()}.
+#'
+#' @examples
+#' \donttest{
```
Comment (Alon-Alexander) [inline R/binary_beta.R]: Why?

**Review by Alon-Alexander — COMMENTED** [review]
Overall looks really solid - code quality definitely improved massively.
I did stop early because it took a long time and my focus is limited.

I also think we should start working with a bit smaller PRs (this one includes many features), especially when there's new code (and not refactoring of old code).
We should also start having documented versions and NEWS.md (which is really not that bad to keep track of).

File: tests/testthat/test-binary_alpha.R
[the remark this answers is not in the document]
Comment (Polymerase3) [reply tests/testthat/test-binary_alpha.R]: Changed. Also improved coverage to ~97% locally.

File: R/binary_beta.R [hunk 12]
```diff
@@ -0,0 +1,2567 @@
...
+  .ph_log_info(
+    paste0("auto-detected `value_col = \"", value_col, "\"` from `ps`.")
+  )
+}
+
+if (!value_col %in% dat_cols) {
+  .ph_abort(
+    paste0("column `", value_col, "` not found in `ps`.")
+  )
+}
```
[the remark this answers is not in the document]
Comment (Polymerase3) [reply R/binary_beta.R]: Reformatted with styler

File: R/binary_beta.R (hunk 1 above)
Comment (Polymerase3) [reply R/binary_beta.R]: Yeah, but in the end you still have to collect the large table into memory. So the only real gain is postponing the collect() and doing the pivot on the duckdb side. I changed it and it hasn’t caused any problems so far, but that might not hold for larger datasets.

File: R/binary_beta.R (hunk 3 above)
Comment (Polymerase3) [reply R/binary_beta.R]: Done

File: R/binary_beta.R [hunk 13]
```diff
@@ -0,0 +1,2567 @@
...
+      norm_mat,
+      method  = dist_method,
+      threads = n_threads
+    )
+
+  } else {
+    dist_obj <- vegan::vegdist(norm_mat, method = dist_method)
+  }
+
+.ph_log_info("distance matrix computation complete.")
```
[the remark this answers is not in the document]
Comment (Polymerase3) [reply R/binary_beta.R]: Hmmm, you are right. Before I began writing R packages, I used R mainly for linear statistical analysis code; that’s probably why my style evolved like this, and why I tend to pack everything into big functions. Your idea about abstraction levels and orchestrator functions makes a lot of sense. Refactoring everything again using this principle would be really time-consuming; maybe at some point, but not now. I’ll try to write new code according to this principle, though. Thanks!

File: R/binary_beta.R (hunk 5 above)
Comment (Polymerase3) [reply R/binary_beta.R]: Opened new issue on this

File: R/binary_beta.R [hunk 14]
```diff
@@ -0,0 +1,2567 @@
...
+      "Distances modified using %s correction prior to PCoA.",
+      neg_correction
+    )
+  } else {
+    "No negative eigenvalue correction applied."
+  }
+
+  if (is_corrected) {
+    .ph_warn(correction_note)
+  }
```
[the remark this answers is not in the document]
Comment (Polymerase3) [reply R/binary_beta.R]: Done

File: R/binary_beta.R [hunk 15]
```diff
@@ -0,0 +1,2567 @@
...
+#'   applicable. This should be a \emph{categorical} factor for this function
+#'   (continuous time not supported).
+#' @param subject_col Name of the subject identifier column in \code{ps}
+#'   (for repeated measures). Default \code{"subject_id"}. If this column is
+#'   present and \code{time_col} is provided, permutations will be stratified by
+#'   subject. This is a simplification and does not implement a full
+#'   repeated-measures permutation design (see Details).
+#' @param permutations Number of permutations for significance testing
+#'   (default 999).
+#' @param p_adjust P-value adjustment method applied within each contrast scope.
```
[the remark this answers is not in the document]
Comment (Polymerase3) [reply R/binary_beta.R]: I think the current [tidyverse style guide](https://style.tidyverse.org/files.html) prohibits reusing the names and also prohibits using `.` as delimiter in the argument names (or at least enforces, that the usage is consistent across the whole package - i am not really sure)
